# Folder of images to process
src_folder: /home/benjamin/datasets/test/
dst_folder: /home/benjamin/datasets/test/output/
save_folder: /home/benjamin/threat_detection/pose_detection/results/

single_image: /home/benjamin/datasets/Aggressiveness/test_images/logitec001_20190506.png
single_filename: logitec001_20190506


# yolo_savefile: /home/benjamin/datasets/Aggressiveness/coco.jpg
coco_data: /home/benjamin/ros/src/usma_threat_ros/yolo/coco-v3.data
coco_config: /home/benjamin/ros/src/usma_threat_ros/yolo/coco-v3.cfg
coco_weights: /home/benjamin/ros/src/usma_threat_ros/yolo/coco-v3.weights

# yolo_savefile: /home/benjamin/datasets/Aggressiveness/pistol.jpg
yolo_data: /home/benjamin/ros/src/usma_threat_ros/yolo/pistol.data
yolo_config: /home/benjamin/ros/src/usma_threat_ros/yolo/pistol-tiny.cfg
# yolo_weights: /home/benjamin/ros/src/usma_threat_ros/yolo/20190506/pistol-yolov3-tiny_100000.weights
# yolo_weights: /home/benjamin/ros/src/usma_threat_ros/yolo/20190506/pistol-yolov3-tiny_150000.weights
# yolo_weights: /home/benjamin/ros/src/usma_threat_ros/yolo/20190506/pistol-yolov3-tiny_200000.weights
yolo_weights: /home/benjamin/ros/src/usma_threat_ros/yolo/20190506/pistol-yolov3-tiny_250000.weights
# yolo_weights: /home/benjamin/ros/src/usma_threat_ros/yolo/20190506/pistol-yolov3-tiny_300000.weights
# yolo_weights: /home/benjamin/ros/src/usma_threat_ros/yolo/20190506/pistol-yolov3-tiny_350000.weights
# yolo_weights: /home/benjamin/ros/src/usma_threat_ros/yolo/20190506/pistol-yolov3-tiny_400000.weights
# yolo_weights: /home/benjamin/ros/src/usma_threat_ros/yolo/20190506/pistol-yolov3-tiny_450000.weights
# yolo_weights: /home/benjamin/ros/src/usma_threat_ros/yolo/20190506/pistol-yolov3-tiny_500000.weights
# Original weights
# yolo_weights: /home/benjamin/ros/src/usma_threat_ros/yolo/pistol-tiny_last.weights
# yolo_weights: /home/benjamin/ros/src/usma_threat_ros/yolo/pistol-tiny_300000.weights

# testing images
# single_image: /home/benjamin/datasets/Aggressiveness/High_ordered/images/high_aggressive_000013.jpg
# single_image: /home/benjamin/datasets/Aggressiveness/Low_ordered/images/low_aggressive_000003.jpg


# good images to use for paper:
# single_image: /home/benjamin/datasets/Aggressiveness/High_ordered/images/high_aggressive_000056.jpg
# single_filename: high_aggressive_000056
# single_image: /home/benjamin/datasets/Aggressiveness/High_ordered/images/high_aggressive_000070.jpg
# single_filename: high_aggressive_000070
# single_image: /home/benjamin/datasets/Aggressiveness/High_ordered/images/high_aggressive_000156.jpg
# single_filename: high_aggressive_000156

# single_image: /home/benjamin/datasets/Aggressiveness/High_ordered/images/high_aggressive_000190.jpg
# single_filename: high_aggressive_000190



