# directory of folder with original file name (ends with '/')
original_path: /home/benjamin/threat_detection/datasets/Aggressiveness/Low/
# original_path: /home/benjamin/threat_detection/YOLOtools/readme_figs/

# where to put renamed images (ends with '/')
renamed_path: /home/benjamin/threat_detection/datasets/Aggressiveness/Low_ordered/
# renamed_path: /home/benjamin/threat_detection/YOLOtools/

# numbers will be appended, suggests ends with '_'
renamed_prefix: low_aggressive_

