# directory of folder with original file name (ends with '/')
original_path: /home/benjamin/datasets/pistol600/jpg/

# where to put renamed images (ends with '/')
renamed_path: /home/benjamin/datasets/pistol600/unsorted/

# numebrs will be appended, suggests ends with '_'
renamed_prefix: unsorted_pistol_

